{% set version = "1.10" %}

package:
  name: pfitmap-db
  version: {{ version }}

source:
  url: https://github.com/erikrikarddaniel/pfitmap-db/archive/v{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - r-dplyr=1.0.7
    - r-dbplyr=2.1.1
    - r-data.table=1.14.2
    - r-rsqlite=2.2.8
    - r-optparse=1.7.1
    - r-purrr=0.3.4
    - r-feather=0.3.5
    - r-readr=2.1.1
    - r-stringi=1.7.6
    - r-stringr=1.4.0
    - r-tidyr=1.1.4
    - bioconductor-biostrings=2.62.0
    - gawk=5.1.0
