{% set version = "1.9.15" %}

package:
  name: pfitmap-db
  version: {{ version }}

source:
  url: https://github.com/erikrikarddaniel/pfitmap-db/archive/v{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - r-dplyr = 1.0.7
    - r-dbplyr = 2.1.1
    - r-data.table = 1.14.2
    - r-rsqlite = 2.2.9
    - r-optparse = 1.7.1
    - r-purrr = 0.3.4
    - r-feather = 0.3.5
    - r-stringi = 1.7.6
    - r-stringr = 1.4.0
    - bioconductor-biostrings = 2.60.2
    - gawk
